<?php

/**
  function intel_facet_enhancement_preprocess_page(&$variables) {
  if (arg(0) == 'solutions-directory') {
  // Add js
  drupal_add_js(drupal_get_path('module', 'intel_facet_enhancement') . '/script.js');
  drupal_add_css(drupal_get_path('module', 'intel_facet_enhancement') . '/style.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
  $variables['scripts'] = drupal_get_js();
  $variables['styles'] = drupal_get_css();
  print_r($variables['styles']);
  }
  }
 * */
function intel_facet_enhancement_init() {

  if (arg(0) == 'solutions-directory' || arg(0) == 'member-roster') {
    drupal_add_js(drupal_get_path('module', 'intel_facet_enhancement') . '/script.js');
    //drupal_add_css(drupal_get_path('module', 'intel_facet_enhancement') . '/style.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
  }
}
